# Site settings
title: Lee, Seo
description: 'Business Card Page'
url: 'http://thomas.zuehlke.family'
baseurl: ''
profilepic: '/images/avatar2.jpg'
bkimage: '/images/avatar3.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '52f361e427.js'

author:
  name: 'Lee, Seo'
  email: info@goyangfree.com
  twitter_username: profile.php?id=100012284628798
  facebook_username: profile.php?id=100012284628798
  intsagram_username:  profile.php?id=100012284628798
  soundcloud_username: user-409382117
  youtube_name: c/TwosQuare투스퀘어/

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
